### ISSUE TITLE
Support for removed items

### ISSUE THREAD

**Issue by MicTech** [AOEpeople/aoe_technology_radar#110]
Is there support for deleted items?

We sometimes remove items from our radar to keep them clean. For instance, if something was moved from "adopt" to "hold" we'd like to remove it from our radar after a while or when we drop some service from our infrastructure. We don't want to remove it from all versions because we'd like to keep it for future references and not change released radar versions.

Thank you

**Comment by bastianccm** [comment]
Hey @MicTech ,

we usually use the `featured` flag: if it's set to `false`, it is not shown on the start page, but kept in the list of items.
Does that help you?

**Comment by mathiasschopmans** [comment]
I will close this ticket as the workflow via setting the `featured: false` flag seems to be working well. 👍
