### ISSUE TITLE
Config: improve default config values

### ISSUE THREAD

**Issue by bastianccm** [AOEpeople/aoe_technology_radar#113]
Unknown config values with the current main branch may fail users, as configuration options are undefined.
We need a better way to handle default config options I think?

**Comment by d-koppenhagen** [comment]
Probably the best would be to define always some fallback/default values and document them in the example config and README.
This would prevent runtime errors.
It could be logged too such as `console.warn('no value defined for', foo, 'falling back to default value', defaultVal)`.

**Comment by bastianccm** [comment]
Yes exactly, also because the radar chart has quite some more settings which might fail if an old configuration is used.
Something like `config = Object.assign({default}, config)` might be even enough?

**Comment by mathiasschopmans** [comment]
Default config will now be extended by user config, so now we have some fallback for new values, which are not defined in the user's project.

See https://github.com/AOEpeople/aoe_technology_radar/commit/04053c6700d9b57c7ad769670658135b02c7709b#diff-0b4f5977a52cef50ed20e7cdf9761795df9ee1cb3b5e5ea45edeb9394e8a47ff
