### ISSUE TITLE
Item History

### ISSUE THREAD

**Issue by Kodrafo** [AOEpeople/aoe_technology_radar#12]
I cannot see anything in the UI how you show history.
In your readme.md you wrote:
"Show item history on details (relevant with 2nd release)"

Does that mean that till now there is no UI support for history at all in the solution?

It would be great if the history feature would be implemented.

**Comment by tomraithel** [comment]
We are currently gathering relevant items for the second AOE techradar release. Therefore the "history" feature is not yet activated for the master branch. The [next](https://github.com/AOEpeople/aoe_technology_radar/tree/next) branch already contains updated items and a history functionality, however nothing in this branch is final and may be changed sooner or later.

**Comment by Kodrafo** [comment]
That looks good! Thanks a lot for your hint.
