### ISSUE TITLE
Slow animations make the tech radar unusable

### ISSUE THREAD

**Issue by ivanmcgregor** [AOEpeople/aoe_technology_radar#132]
When using the tech radar, it sometimes does unbearably slow animations that make it really frustrating to use. This happens whenever a section is opened and when it is closed again, the same animations run backwards.

Just opening the first entry will trigger a multitude of animations, taking a total of 3 seconds. UX research has shown that fast interactions should take around 200ms, animations that are moving huge portions of the screen can be slower, so 500ms is recommended.

**Comment by bastianccm** [comment]
Hey @ivanmcgregor thank you for taking time to file an issue.
As this is an open source project, we’re happy to have contributions or concrete suggestions on how to improve.

**Comment by lmestre-td** [comment]
I know this is a current issue right now, my suggestion would be to change the animation library. In my implementation I changed it for the react-spring library and it works smoothly

**Comment by bastianccm** [comment]
@lmestre-td would you like to contribute this to the radar?
