### ISSUE TITLE
Fadeout creates new revision and duplicates description

### ISSUE THREAD

**Issue by srotsch** [AOEpeople/aoe_technology_radar#134]
When fading out an issue (by adding "featured: false" to the header section), a new revision will be created. As no additional text is provided, the description will be duplicated in the generated radar, eg.

Commit: https://github.com/AOEpeople/techradar/blob/710a17b6d89b630d5858e7bd80cbfe5a932e286e/radar/2019-11-01/dagger.md?plain=1
Result: https://www.aoe.com/techradar/tools/dagger.html

Expected behavior: a fadeout should not add a new revision if neither quadrant nor ring changed; the blip should only be removed from the radar view.

**Comment by danielpoe** [comment]
Expected behavior: a fadeout should not add a new revision if only the featured flag changed.
(neither quadrant nor ring, nor a description added)
