### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by Kodrafo** [AOEpeople/aoe_technology_radar#14]
We love your tech radar and it inspired us to create our own tech radar based on your work.
Therefore we created a fork. You can see the result  [here](https://github.com/Haufe-Lexware/aoe_technology_radar). The running version is [here ](http://techradar.haufe.io/techradar/radar-chart.html).
We made lot of changes and adapted the content for our use case.
We want to publish the Tech Radar in our company. And we plan to leave it accessable by everybody.

I just wanted to add license information to our GitHub fork and realized that I can't find license infos on your repo.
We want to provide it under the Apache 2.0 license like we did [here](https://github.com/Haufe-Lexware/wicked.haufe.io/blob/master/LICENSE)?
How did you want to offer your work and can you add license information?
Do you see any problems that we publish our Haufe Tech-Radar?

**Comment by danielpoe** [comment]
Hello

Nice that you liked our work - and thanks for asking.
I will clearify and come back with infos regarding the OS license.

What would be good please is to adjust CI a bit before publishing - the colors and fonts are AOE CI and would be good to change it - to not look too close to our radar.

Cheers,
Daniel

**Comment by Kodrafo** [comment]
Hello Daniel,

Thanks a lot for your quick answer. I will change the colors and fonts so that it fits to our corporate CI.
That was a good hint!

Cheers
Rainer

**Comment by Kodrafo** [comment]
The radar CI is now adapted on our own CI. Colors and fonts are changed.

Cheers Rainer

**Comment by BernhardBehrendt** [comment]
Hey @Kodrafo license has been updated to Apache-2.0 in next branch with commit 97c97a9.
This will be merged to master soon.
