### ISSUE TITLE
Enable dependabot for this repo

### ISSUE THREAD

**Issue by onikiienko** [AOEpeople/aoe_technology_radar#142]
Hi! Your project saves me tone of time, thanks a lot🏆

My idea is to add https://github.com/dependabot to this repo.
I have only your project in my radar dependencies and am faced with a few security issues which can be fixed with deps update
<img width="968" alt="Screenshot 2022-05-10 at 00 39 36" src="https://user-images.githubusercontent.com/3531246/167503095-b7695b3d-8752-473a-8e1b-cb559d497a91.png">

**Comment by bastianccm** [comment]
Hey @onikiienko 

Took a while to find time to upgrade everything to react 18, now we should be down to 1 medium severity which is introduced by a transitive dependency of react-scripts: https://github.com/facebook/create-react-app/issues/11174

I'll release the latest version as v3.3.0, which should include all updates (and switches to npm for package management).

**Comment by bastianccm** [comment]
I also added renovate to keep all dependencies up to date, once react-scripts have the update we'll get it too
