### ISSUE TITLE
deterministic behaviour for radar

### ISSUE THREAD

**Issue by bastianccm** [AOEpeople/aoe_technology_radar#148]
instead of random create position from hash(item)?

**Comment by onikiienko** [comment]
Hi! I think that static position for blips is a wonderful feature, so I've tried to update it to the latest version of your magic tool. 

And it seems that it started to choose worse positions for blips, it looks a bit "collapsed" now than it was made by d3, especially if the radar contains a lot of items. Is there a way to fix this issue?

This is the view from the previous version
<img width="1245" alt="Screenshot 2023-06-22 at 19 49 37" src="https://github.com/AOEpeople/aoe_technology_radar/assets/3531246/8dda315d-d133-477a-8549-fa0dd91d70a8">

And is I've with the latest
<img width="1233" alt="Screenshot 2023-06-22 at 19 49 26" src="https://github.com/AOEpeople/aoe_technology_radar/assets/3531246/80de85fa-6c09-42aa-b82b-4d9b9d951097">
