### ISSUE TITLE
Contents missing in generated static html files

### ISSUE THREAD

**Issue by midhundkumar** [AOEpeople/aoe_technology_radar#190]
Generated the static html files for s3 hosting as per the documentation provided.
But the htmls generated have the common body contents, which is empty

Has anyone already ran into the issue? And if so, any valid solution to fix the same??

Attaching one of the generated static **file:**
![Screenshot from 2022-08-01 19-38-16](https://user-images.githubusercontent.com/65619091/182166466-abbc6e3c-0968-4826-af01-563322cb33fa.png)

**Comment by bastianccm** [comment]
Hi @midhundkumar ,

sorry for catching up so late. Does the issue still exist?

**Comment by bastianccm** [comment]
#164
