### ISSUE TITLE
Bug: quadrants colours are incorrect

### ISSUE THREAD

**Issue by onikiienko** [AOEpeople/aoe_technology_radar#254]
Seems like after these changes we have the incorrect match of colours between blips and quadrants 
https://github.com/AOEpeople/aoe_technology_radar/commit/36b63db14d6955b0460995fc0bd601320d71f972
<img width="1275" alt="Screenshot 2022-11-15 at 21 20 15" src="https://user-images.githubusercontent.com/3531246/202006884-498876d3-7bd5-4bfa-a500-9f10de1c08c3.png">

**Comment by bastianccm** [comment]
oh right, that must have slipped in plain sight. I'll get a fix ready

**Comment by bastianccm** [comment]
fixed in v3.4.1
