### ISSUE TITLE
Change the ring names using config.json, then you lose the badge colors

### ISSUE THREAD

**Issue by nocquidant** [AOEpeople/aoe_technology_radar#286]
See screenshots below.

--- Screenshot 1
![image](https://user-images.githubusercontent.com/217054/210087950-e41feae5-68ab-4538-a189-ca46432fc95d.png)

--- Screenshot 2
![image](https://user-images.githubusercontent.com/217054/210087989-02f290ef-0a31-4861-9924-d4455d7093dc.png)

--- Screenshot 3
![image](https://user-images.githubusercontent.com/217054/210088021-4ae96e8e-ab03-4b99-aff3-bcc2d9eedc48.png)

**Comment by bastianccm** [comment]
Thanks for reporting @nocquidant, it should be resolved with v3.5.0

**Comment by nocquidant** [comment]
Yes! Thank you
