### ISSUE TITLE
Generated HTML should work in a subpath

### ISSUE THREAD

**Issue by danielpoe** [AOEpeople/aoe_technology_radar#3]
Goal is to run it under www.aoe.com/tech-radar/

**Comment by tomraithel** [comment]
@mathiasschopmans you fixed that with 13236109822db086a3deb3eaba65cfde387f005e right?

**Comment by mathiasschopmans** [comment]
@tomraithel Jup. It should work for now, but might not be the ideal solution. 🙈

**Comment by tomraithel** [comment]
I think it´s fine for the first release -> done
