### ISSUE TITLE
No content in generated static html files

### ISSUE THREAD

**Issue by d-koppenhagen** [AOEpeople/aoe_technology_radar#327]
Probably this is related to: #190

## reproduction steps

1. clone the [techradar-repo](https://github.com/AOEpeople/techradar) which inlcudes the `aoe_technology_radar` package
2. run `npm i` to install dependencies
3. generate static sites: `npm run build:static`

The output of every technology static page looks like this:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="/favicon.ico" />
    <meta name="theme-color" content="#000000" />
    <meta name="description" content="AOE Technology Radar" />
    <link rel="apple-touch-icon" href="/logo.svg" />
    <link rel="stylesheet" href="/fonts.css" />
    <link rel="stylesheet" href="/styles.css" />
    <meta property="og:title" content="AOE Technology Radar" />
    <meta property="og:image" content="/logo.svg" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <title>AOE Technology Radar</title>
    <script defer="defer" src="/static/js/main.8158d222.js"></script>
    <link href="/static/css/main.7f6950a9.css" rel="stylesheet" />
  </head>
  <body>
    <noscript
      >You need to enable JavaScript to view the AOE Technology Radar.</noscript
    >
    <div id="root"></div>
  </body>
</html>
```

**Comment by d-koppenhagen** [comment]
Actually it seems there is only a basic index.html file copied to every page target but the content is not extracted anywhere: https://github.com/AOEpeople/aoe_technology_radar/blob/main/scripts/createStaticFiles.ts

**Comment by srotsch** [comment]
@bastianccm As discussed today this is also the reason for LinkedIn e.a. not being able to render a proper link preview.

![Bild eingefügt am 2023-3-3 08-44](https://user-images.githubusercontent.com/1445999/222741992-15bed57a-d2e6-40a4-8eec-ea461ec50260.png)

**Comment by bastianccm** [comment]
Hey guys, reason is that there is no actual static rendering, but instead just an entrypoint for react. This is fine for Google, but obviously not for Linkedin & co.
I'll have a look what work is required to run something like next to pre-build actual content into the pages and keep you updated!

**Comment by edgarvonk** [comment]
Hi, I think related to this is the fact that overriding the /public/index.html file as per README.md does not seem to work? When we do so the resulting index.html file in the /build folder is simply a copy of this template file and does not get processed at all.
