### ISSUE TITLE
replace xml-sitemap with something newer

### ISSUE THREAD

**Issue by bastianccm** [AOEpeople/aoe_technology_radar#359]
Last release was 6 years ago, and xmljs is prune to prototype pollution, we should update to a newer XML sitemap generator

**Comment by mathiasschopmans** [comment]
The version 4.0.0 eliminated the generation of a sitemap.xml, but relies on superb static site generation via next.js.

> Do sites really need a sitemap.xml?
> Almost never.  

https://www.imarc.com/blog/do-sites-really-need-a-sitemap-for-seo

If there's still a need for sitemaps, we may re-add this feature without any external dependencies. 🙏 

![sitemap xml doesn't help seo - change my mind](https://www.imarc.com/writable/images/thought-featured-images/blog-do-sites-need-a-sitemap.jpg)
