### ISSUE TITLE
Blips are overlapping each other after changes in the latest release

### ISSUE THREAD

**Issue by onikiienko** [AOEpeople/aoe_technology_radar#393]
Hi!
I do like a lot the idea of [deterministic behavior for radar by storing the random fractions when generating rd.json](https://github.com/AOEpeople/aoe_technology_radar/pull/372) introduced in the [v3.5.3](https://github.com/AOEpeople/aoe_technology_radar/releases/tag/v3.5.3)

But, unfortunately, I've faced a problem with blips overlapping. Especially when those blips are many.
It seems that chosen approach started to pick worse coordinates for blips, it looks a bit "collapsed" now than it was made by d3 while rendering the chart. Is there a way to fix this issue, or, at least, switch off storing the random fractions?

I could see the same situation [www.aoe.com/techradar](http://www.aoe.com/techradar) but it is less critical because of a number of blips.

---
v3.5.2
<img width="1245" alt="Screenshot 2023-06-22 at 19 49 37" src="https://github.com/AOEpeople/aoe_technology_radar/assets/3531246/f0cf562f-6adc-4a5c-bac1-9afe2b760c1b">

---
v3.5.3
<img width="1233" alt="Screenshot 2023-06-22 at 19 49 26" src="https://github.com/AOEpeople/aoe_technology_radar/assets/3531246/f6af5ac7-0be2-46b2-82e1-57cbb2011048">

**Comment by srotsch** [comment]
Confirmed, even with the smaller amount of blips on our radar.

We'll investigate how to solve this. Ideally, the blips would behave like atoms or magnets with equal poles and repel to maintain a minimum distance.

Out of curiosity: how many items do you have on the radar at the moment?

**Comment by onikiienko** [comment]
It's 290 items on the radar at the moment

**Comment by onikiienko** [comment]
Hi, @srotsch! are there any updates on this issue? Do you need any additional information from my side?

**Comment by srotsch** [comment]
Hi @onikiienko! Nothing to do on your side, it's us being busy with other things… sorry about that. But as we're planning to release a new version of our technology radar within the next couple of weeks, we're committed to fix this issue as soon as possible. Thanks for the reminder and your patience.

**Comment by onikiienko** [comment]
Great! Thanks, looking for further news🙌

**Comment by mathiasschopmans** [comment]
Fingers crossed that the new version 4.0.0 also reduces the problem of overlapping entries to a minimum for you. ✊

**Comment by onikiienko** [comment]
I'll try to upgrade to the latest version. You rock, guys!
