### ISSUE TITLE
Refinement of filtering

### ISSUE THREAD

**Issue by belimposition** [AOEpeople/aoe_technology_radar#410]
Hi. I would like to be able to filter by tags not only as AND, but also as OR
some kind of switch or something
Thanks

**Comment by mathiasschopmans** [comment]
We reworked the filter in the v4.0.0. The new filter is now directly part of the homepage content and acts like a radio button; selecting one tag at a time. 

![screenshot-techradar](https://github.com/AOEpeople/aoe_technology_radar/assets/193253/4f8a9b0a-c557-40da-adea-e869edbc44b3)

So currently there's no need to implement the logic, but if there's a request of having multiple selected tags, we will rework this like you suggested (OR-logic): Showing all items, containing at least one of the selected tag.
