### ISSUE TITLE
color of .ring-label can not be defined by CSS

### ISSUE THREAD

**Issue by Strese7** [AOEpeople/aoe_technology_radar#416]
The text in "svg g .ring-label text" elements is always white and can't be set by any CSS rule. How is about SVG attribute fill="currentColor" in the text tag?. Any other solution?

**Comment by mathiasschopmans** [comment]
Hello @Strese7,

Utilizing currentColor is a valid approach to ensure that the text color within your SVG adapts based on the current color context. However, if you prefer a more straightforward solution, you can directly assign a color through CSS. The key is to ensure your CSS selector accurately targets the desired elements. Based on your description, it appears there may have been a slight misunderstanding in the use of selectors.

Given the structure 

```html
<g class="ring-label">
  <text x="500" y="400" text-anchor="middle" dy=".35em">adopt</text>
</g>
```

the correct CSS rule to change the text color should look like this:

```css
svg g.ring-label text {
    fill: #bada55;
}
```

or simply
```css
.ring-label {
  fill: #bada55;
}
```

This rule specifically targets text elements within a g element that has the class ring-label.
The initial confusion might have arisen from a misplaced space in the selector, which implies a different relationship between the elements than what is actually present in your SVG structure.

By refining the selector to `svg g.ring-label text` —thereby removing the unnecessary `space` after `g` and directly specifying the class— it should correctly apply the desired color to your text elements.

```diff
- svg g .ring-label text
+ svg g.ring-label text 
```

Should you have any further questions or require additional assistance, please don't hesitate to ask and reopen the issue.

Best,
Mathias
