### ISSUE TITLE
RadarGrid Legend can't be translated

### ISSUE THREAD

**Issue by Strese7** [AOEpeople/aoe_technology_radar#417]
The RadarGrid Legend seems to be fixed in code and can't be translated in the config.json, we need it in German. Any suggestions?

**Comment by mathiasschopmans** [comment]
We just released v4.0.0 which is a complete rewrite of the existing application and allows you to set the label via `config.json` : `flags.new.description`, `flags.changed.description`, `flags.default.description` 

See https://github.com/AOEpeople/aoe_technology_radar/blob/main/data/config.json#L79

To update your radar, I advise you to create a new project by creating a `package.json` with the following contents:
```json
{
  "name": "aoe-techradar",
  "version": "1.0.0",
  "license": "MIT",
  "scripts": {
    "build": "techradar build",
    "serve": "techradar serve"
  },
  "dependencies": {
    "aoe_technology_radar": "^4"
  }
}
```

Run `npm install` & `npm run`, modify the created `config.json` and replace the `radar` folder with your existing items.
