### ISSUE TITLE
v4: build fails with "cannot find module '@/components/Icons/Close' or its corresponding type declarations"

### ISSUE THREAD

**Issue by DanielRuf** [AOEpeople/aoe_technology_radar#435]
![grafik](https://github.com/AOEpeople/aoe_technology_radar/assets/827205/c56fcd34-2e5a-4958-b174-4403a4a8cabd)

**Comment by DanielRuf** [comment]
There is definitely no `Icons` folder:

https://github.com/AOEpeople/aoe_technology_radar/tree/main/src/components

![grafik](https://github.com/AOEpeople/aoe_technology_radar/assets/827205/6acffa31-f60b-43f1-ae6f-0c636fbad127)

**Comment by mathiasschopmans** [comment]
Yes, this components are not tracked, but created dynamically via npm postinstall script.

See package.json line 16
```
    "postinstall": "npm run build:icons"
```

Did you build the radar directly, or did you create a new project using the aoe_technology_radar as dependency?

**Comment by DanielRuf** [comment]
Ah, that explains it. I have disabled scripts for security reasons. Thanks for the information, I will manually run `npm run build:icons`.

**Comment by DanielRuf** [comment]
Hm, any good reasons why the postinstall script is used instead of precompiling the icon and putting them in the releases as part of the publishing process on npmjs?

Because now we have to either enable scripts again or switch to npm, because the npx command may not work in CI, since it asks to install the svgr-cli. Without adding `--yes` we might have to do some tricks or run the underlying command directly.

**Comment by mathiasschopmans** [comment]
I will try the svgr loader with turbopack again, to not precompile the icon components. The last time I tried it, it was not supported therefore I used the workaround via cli.

Alternatively we could track the compiled icons in git.
