### ISSUE TITLE
v4: sitemap.xml missing

### ISSUE THREAD

**Issue by DanielRuf** [AOEpeople/aoe_technology_radar#438]
With the new Next setup, there is no `sitemap.xml` file generated.

See https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap#generating-a-sitemap-using-code-js-ts for context.

**Comment by mathiasschopmans** [comment]
I'm not sure of the value of having a sitemap.xml. Google says you might not need an XML sitemap if:

- Your site is comprehensively linked internally. ✅ 
- You don’t have many media files (video, image) or news pages that you need to appear in the index. ✅ 
- Your site is “small”: By small, we mean about 500 pages or less on your site. ✅  (AOE's Techradar has around ~250 pages)

https://builtin.com/marketing/sitemap-xml-overrated

The v3 implementation did not align to the sitemap.xml spec, as it created relative URLs. 

> `<loc>`: URL of the page. This URL must begin with the protocol (such as http) and end with a trailing slash, if your web server requires it. This value must be less than 2,048 characters.

https://www.sitemaps.org/protocol.html#locdef

ℹ️  To generate a valid sitemap.xml, we need to introduce a new setting: `config.baseUrl`.

**Comment by mathiasschopmans** [comment]
I created a PR. Does this meet your expectation, @DanielRuf?
