### ISSUE TITLE
[idea] possibility to override single templates

### ISSUE THREAD

**Issue by DanielRuf** [AOEpeople/aoe_technology_radar#441]
It seems there is no support to extend or override single parts like header and footer.

What is the recommended solution?

**Comment by mathiasschopmans** [comment]
This feature is currently not planned. 

My gut feeling is that copying React components from a user project to the build folder, as we do for `config.json` and the markdown files, is not stable and will quickly lead to frustration during updates.

Do you have an idea in mind how you would implement it?

**Comment by DanielRuf** [comment]
> Do you have an idea in mind how you would implement it?

Not really, to be honest. I didn't work with Next so far.
