### ISSUE TITLE
Clarify Licensing Terms for Articles

### ISSUE THREAD

**Issue by allentiak** [AOEpeople/aoe_technology_radar#47]
Just wondering...
Your repo includes both code and articles. The code is ASL 2.0. What is the license for the articles? Is it CC BY-SA? Is it CC BY? Is it something else?

CC Licenses: https://creativecommons.org/licenses/

**Comment by bastianccm** [comment]
Hey @allentiak 
thank you for bringing this up! We will clarify it of course!

**Comment by bastianccm** [comment]
Hi @allentiak,

a little late, but we decided for `CC BY-NC-SA` for the time being.
We will add a copyright note to the articles.

The code itself stays ASL 2.0.

**Comment by allentiak** [comment]
Thanks for the update, @bastianccm !
Looking forward to the update.
