### ISSUE TITLE
Logo sometimes breaks, e.g. when navigating between blips

### ISSUE THREAD

**Issue by stefanes** [AOEpeople/aoe_technology_radar#481]
In some instances the logo is broken, e.g. when navigating between blips using markdown syntax like so:

```markdown
[Terraform](/platforms-and-operations/terraform/)
```

A 404 error is logged, and the only way to get the icon back is to go back to the root page and refresh.

![image](https://github.com/user-attachments/assets/da012b92-4bcb-4788-9d8b-499e58a052ee)

![image](https://github.com/user-attachments/assets/3e699c4a-2b04-4641-88f8-4f3e07105db0)

**Comment by onikiienko** [comment]
I had the same issue yesterday. I assume that you have `"basePath": "/",` in your config, then try to use `"logoFile": "/logo.svg",` instead of `"logoFile": "logo.svg",`
