### ISSUE TITLE
Putting all Techradar data in every rendered HTML will eat up disk space with big radars

### ISSUE THREAD

**Issue by snipem** [AOEpeople/aoe_technology_radar#50]
We have a demo installation with about 200 items in the techradar. Putting every item and item description in every rendered html file of the techradar will easily eat up disk space. Currently this is done for initialising the Redux State Container in https://github.com/AOEpeople/aoe_technology_radar/blob/master/js/server.js#L51.

This is a concern with static page hosts like Github Pages or Gitlab Pages. The latter fails when pages exceed 100 MB.

We had a case where every rendered HTML file was about 500KB. With 200 items in the techradar the 100 MB max size was easily exceeded.

**Comment by bastianccm** [comment]
Hi @snipem 

Now the radar json is compiled into the assets, and the index.html is a much smaller entry point.
There was some refactoring, so you probably want to check out the changes.

Please see https://github.com/AOEpeople/aoe_technology_radar/#run-a-prepared-static-version for an example.

Currently (for our AOE techradar) we have ca. 2.6kb per html page. The radar data will be fetched afterwards. Hope this helps?

**Comment by bmsuseluda** [comment]
Hello @snipem we changed the loading of the json file, so that it will be fetched by the application. Therefore the browser can cache the file and the htmls don't have the data in itself.
I will close the issue. If you have problems with the current solution, let me know here and i can reopen the issue.
