### ISSUE TITLE
Parameterized baseUrl location

### ISSUE THREAD

**Issue by lacy-llana** [AOEpeople/aoe_technology_radar#59]
I'm having some troubles getting this to deploy and behave correctly using Gitlab pages to host. 

For example, due to the repo structure within my organization's Gitlab group, the base URL where the site will be deployed looks like: 

https://company-engineering.gitlab.io/teams/engineering/tools/tech-radar

It looks like the fix for your implementation was to hard code 'techradar' into a number of the file paths, however if I were to replace that with the full string represented in my URL above, it doesn't load locally properly. 

It would be ideal to pass in a base URL in the config that would inform the file structure/URL path. Examples of this can be found in this repo: https://gitlab.com/pages

**Comment by lacy-llana** [comment]
Another page that might be useful for reference to better describe what I'm talking about: https://docs.gitlab.com/ee/user/project/pages/getting_started_part_one.html#urls-and-baseurls

**Comment by bastianccm** [comment]
Hey @lacy-llana 

You are correct, the tech radar's router currently requires the `techradar/` path.
We just refactored the tech radar, so next will be some proper configuration, and fixing this kind of issues.

**Comment by lacy-llana** [comment]
Thanks @bastianccm - is the refactor available for open source use currently, or are those configuration pieces still in development?

**Comment by bmsuseluda** [comment]
Hey @lacy-llana,
with the current version you can host the application under a sub path with the environment variable PUBLIC_URL.
I documented it in the readme.
Please have a look.

**Comment by bmsuseluda** [comment]
I will close the issue. If you are missing something or have problems, i can reopen the issue.
