### ISSUE TITLE
Feature: Support "tags" in article meta data

### ISSUE THREAD

**Issue by danielpoe** [AOEpeople/aoe_technology_radar#6]
We might want to use it for filtering for only "Frontend" or "Infrastructure" technologies later.

**Comment by derkoe** [comment]
We'd like the same thing to produce different radars for different stakeholders.

I'm currently working on an implementation where you add `radars` to the frontmatter. This can be used to produce different radars with adifferent `config.json` per radar.

**Comment by derkoe** [comment]
Here is the commit for that: https://github.com/porscheinformatik/aoe_technology_radar/commit/5e736c0da1a07dd3f4902ec77f2a852746cfaa51

Would you like me to create a PR for this?

**Comment by bastianccm** [comment]
Hey @derkoe, I think @danielpoe's initial idea was to support those tags on the frontend, having one radar which lets users toggle between different tags.

However, I think your work is a great first step, and if I understand correctly, it's completely backwards compatible. So if you don't mind writing a line to the Readme about that I'm more than happy to welcome a PR!

**Comment by onikiienko** [comment]
This feature with filters might be awesome! Any updates?🙏

**Comment by onikiienko** [comment]
I've prepared a PR with multi tags filtering https://github.com/AOEpeople/aoe_technology_radar/pull/245
