### ISSUE TITLE
Additional tags for filtering

### ISSUE THREAD

**Issue by 4integration** [AOEpeople/aoe_technology_radar#60]
Hi,

Thanks for great solution for TechRadar!

One improvement area that we can see is that the radar can be very large and difficult to read.
A suggestion would be to have additional tags and filtering.
Some components are valid and applicable for all but some are only of interest in a certain area; or if we call them "development track". It could be from tech-stack "java" or ".net" or domains "DataWarehouse", "Application" or "Infrastructure"

Two examples:
```
---
title:      "Apache Hadoop"
ring:       appointed
quadrant:   platforms-and-services
dev_track:  data-warehouse

---
```
or
```
---
title:      "Spring Framework"
ring:       appointed
quadrant:   languages-and-frameworks
dev_track:  java

---
```
And then a possibility to filter on these tags in the UI.

**Comment by onikiienko** [comment]
This is a brilliant idea! I would like to filter by `front-end`, `SRE`, `back-end` etc

**Comment by danielpoe** [comment]
Yes - there is a related issue / idea:
https://github.com/AOEpeople/aoe_technology_radar/issues/6

I would suggest to name the property: "tags" and allow a comma seperated list of tags.
The frontend can show the tags and then highlight/filter the blips.

**Comment by bastianccm** [comment]
I'll close this in favor of #6, which describes the same feature.
As a first start, we will introduce the tags in #140 as a build-time feature, and subsequently add a runtime/frontend switch for flags
