### ISSUE TITLE
Question - How would I modify formatting in the latest release?

### ISSUE THREAD

**Issue by lacy-llana** [AOEpeople/aoe_technology_radar#68]
I've tried replicating both repos (the tech radar contents, and the aoe_technology_radar repos) into my personal Gitlab repos, and referencing the aoe_technology_radar from the techradar repo, but it fails to install yarn packages if I point to my repo path. I'm a bit of a Yarn newbie, but if it requires using the publically published yarn package, how would I go about updating fonts/logos since those are set up in the aoe_technology_radar repo?

**Comment by Zeutschler** [comment]
Hi, cool project but some for me. Maybe some files are missing. e.g.: index.js

when running 'yarn aoe_technology_radar' it says...

$ .../aoe_technology_radar/node_modules/.bin/aoe_technology_radar
Could not find a required file.
  Name: index.js
  Searched in: .../aoe_technology_radar/src
error Command failed with exit code 1.

**Comment by 4integration** [comment]
I get the same error as @Zeutschler

**Comment by bmsuseluda** [comment]
Hello together,
we updated this repo a bit to make it easier to use. I documented what you can customize for your tech radar in the readme, so please have a look if it fits your needs.

In the upcoming version of https://github.com/AOEpeople/techradar/tree/radar-2021-01-01 you can see how we use it.

**Comment by bmsuseluda** [comment]
Version 3 is released with a lot of changes to customize the radar instead of forking it. Please have a look.
I will close this issue. If you are missing something or have problems, i can reopen the issue.
