### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by 4integration** [AOEpeople/aoe_technology_radar#73]
Hi,

I am not able to build the AOE Tech Radar v2.0.
Need to do some changes to fonts, colors etc so therefore a have cloned the repo

```
$ git clone https://github.com/AOEpeople/aoe_technology_radar.git
$ cd aoe_technology_radar
# download all dependencies
$ yarn 
# build
$ yarn build 
```

In package.json it only runs `tsc` but in v1.99 it had a lot of commands that was executed.

How can I build a working tech radar?

**Comment by 4integration** [comment]
```
$ yarn add https://github.com/aoepeople/aoe_technology_radar.git^C

$ yarn aoe_technology_radar
yarn run v1.22.10
warning package.json: No license field
$ /mnt/c/projects/lab/node_modules/.bin/aoe_technology_radar
Could not find a required file.
  Name: index.js
  Searched in: /mnt/c/projects/lab/src
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jar0s** [comment]
Hi @4integration 
> How can I build a working tech radar?

If it's about building to run locally for the development purposes, I figured it out and added some info to the Readme in the above PR.

Here are the steps I took to run a fork of `https://github.com/AOEpeople/aoe_technology_radar` locally:
1. Copy the `src/rd.json_` file and save it as `src/rd.json`.
2. Copy the `src/index.tsx_` file and save it as `src/index.tsx`.
3. Run `./scripts/start` to start a local dev server.
4. Access the local app at [http://localhost:3000/techradar](http://localhost:3000/techradar).

**Comment by 4integration** [comment]
Thanks @jar0s for your input. Tried it but it fails with some strange error below. I am running in WSL (Windows Subsystem for Linux) on Windows10. 

```
Starting the development server...

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn /mnt/c/System32/WindowsPowerShell/v1.0/powershell.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
So I tried to run `build` instead but fails for another reason:

```
$ ./scripts/build.js
start
Built radar
Creating an optimized production build...
Failed to compile.

./src/index.tsx
Cannot find module: 'aoe_technology_radar/src/index.scss'. Make sure this package is installed.

You can install this package by running: yarn add aoe_technology_radar/src/index.scss.
```
What actually want to do is to generate a static site to be published with Nginx in Docker

**Comment by 4integration** [comment]
> ```
> $ yarn add https://github.com/aoepeople/aoe_technology_radar.git
> 
> $ yarn aoe_technology_radar
> yarn run v1.22.10
> warning package.json: No license field
> $ /mnt/c/projects/lab/node_modules/.bin/aoe_technology_radar
> Could not find a required file.
>   Name: index.js
>   Searched in: /mnt/c/projects/lab/src
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```

I have not worked on this for a while but today I did some fresh tries again but get the same error as above.
Normally I run this in WSL (Windows Sub System for Linux) with Ubuntu 20.04 but today I also tested with a plain Ubuntu 20.04 with the same result.

Using:
```
$ nvm --version
0.35.3

$ node -v
v14.17.0

$ npm -v
6.14.13

$ yarn -v
1.22.10
```

**Comment by 4integration** [comment]
Ok, realized there are several repos nowadays ;)
