### ISSUE TITLE
Improve handling of Security headers

### ISSUE THREAD

**Issue by d738** [AOEpeople/aoe_technology_radar#83]
Currently Security Headers like "Strict Transport Security", "X Frame Options" and "Content Security Policy" are not set.

Please have a look at this evaluation and take appropriate actions:
https://snyk.io/test/website-scanner/?test=210625_BiDcFY_34f8de74f6f9696b006eaad0c859e66f&utm_medium=referral&utm_source=webpagetest&utm_campaign=website-scanner

**Comment by bmsuseluda** [comment]
security headers were added. Thanks for the headsup

**Comment by d738** [comment]
Great job. Now it is an A+ rating :-)
