### ISSUE TITLE
Improve network utilization by using compression

### ISSUE THREAD

**Issue by d738** [AOEpeople/aoe_technology_radar#84]
There are potential savings in network usage if compression is used.

Please have a look at this report and consider appropriate actions:
"622.0 KB total in compressible text, target size = 146.7 KB - potential savings = 475.3 KB"

https://www.webpagetest.org/performance_optimization.php?test=210625_BiDcFY_34f8de74f6f9696b006eaad0c859e66f&run=1#compress_text

**Comment by bastianccm** [comment]
Thank you for the heads up, I'm asking the server-people what they can do :)

**Comment by bastianccm** [comment]
https://www.webpagetest.org/result/211111_BiDcNF_1077f7cfc97c5b0fb56b56f182860913/1/performance_optimization/ done
