### ISSUE TITLE
Improve load behaviour by using a suitable caching strategy

### ISSUE THREAD

**Issue by d738** [AOEpeople/aoe_technology_radar#85]
Currently the static assets are lacking any Cache Headers.

Please have a look at this report and consider appropriate actions:
https://www.webpagetest.org/performance_optimization.php?test=210625_BiDcFY_34f8de74f6f9696b006eaad0c859e66f&run=1#cache_static_content

**Comment by bastianccm** [comment]
Thx, we fixed it
