### ISSUE TITLE
Internet Explorer Detail View is broken

### ISSUE THREAD

**Issue by philipfeldmann** [AOEpeople/aoe_technology_radar#9]
From version 11 below.
Is IE support needed? Since it's meant for devs...

![ie-issue](https://cloud.githubusercontent.com/assets/6271103/24695249/4260e85a-19e5-11e7-8d93-03935f58f198.png)

**Comment by DanielRuf** [comment]
> Is IE support needed? Since it's meant for devs...

IE11 is quite old and depending on the OS (Win 7 / 10) you have a different IE11 version which has different bugs.

IE11 does not get any bug fixes anymore and making changes for IE11 is often much work.

**Comment by bastianccm** [comment]
GIven the age I'll close this ticket. If someone is bored we're happy for a fix though ;)
