### ISSUE TITLE
Allow to configure keys/values for quadrants and rings

### ISSUE THREAD

**Issue by d-koppenhagen** [AOEpeople/aoe_technology_radar#96]
Hi, currently the configuration for `rings` and `quadrants` is fixed and cannot be customized easily.
This settings should be configurable as it will may change (either here or within a customized project/fork as PR https://github.com/AOEpeople/aoe_technology_radar/pull/93/files will show).

My suggestion would be to allow placing a JSON-config-file inside the `public` that allows to define customized values to be used (similar to `messages.json`).

E.g.:

`/public/config.json`
```json
{
  "quadrants": {
    "infrastructure-and-tools": "Infrastructure & Tools",
    "languages-and-frameworks": "Languages & Frameworks",
    "foo-bar": "Foo & Bar",
    "baz": "Another Category"
  },
  "rings": ["all", "adopt", "trial", "assess", "hold", "foo", "bar"]
}
```

**Comment by Karreg** [comment]
I endorse this feature and PR! :)
