### ISSUE TITLE
Add a graphical radar

### ISSUE THREAD

**Issue by Karreg** [AOEpeople/aoe_technology_radar#99]
Hello,

Is there any possibility to add a graphical radar in the index page?
For now, I'm working around it by integrating the zalando radar, and generating the radar data from the aoe markdown with a python script, but...
* it's not perfectly integrated, going back to index from aoe pages won't go back to the graphical radar until the page is refreshed
* it's not visually coherent

So having it directly with the AOE techradar would be great!

Thanks, regards.

**Comment by bastianccm** [comment]
Hey @Karreg , it's been a long discussion, and #74 started to address this but collided with the last refactoring. Probably the neatest way would be getting that MR back in shape and making it an option, what do you think?

**Comment by Karreg** [comment]
I think that would be great! The design is really beautiful. I will follow #74 with the biggest interest.
